<table border="1" class="dataframe table table-striped rfm_table">
  <thead>
    <tr style="text-align: right;">
      <th>ID</th>
      <th>Nama Pendonor</th>
      <th>Tanggal Lahir</th>
      <th>Jenis Kelamin</th>
      <th>Golongan Darah</th>
      <th>Rhesus</th>
      <th>Alamat</th>
      <th>Alamat Kantor</th>
      <th>No Telepon</th>
      <th>E-mail</th>
      <th>Recency</th>
      <th>Frequency</th>
      <th>Monetary</th>
      <th>RFM</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>JAMES</td>
      <td>1974-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk@gmail.com</td>
      <td>5</td>
      <td>5</td>
      <td>5</td>
      <td>15</td>
    </tr>
    <tr>
      <td>2</td>
      <td>VERO</td>
      <td>1972-10-01</td>
      <td>L</td>
      <td>B</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221835555</td>
      <td>hahaha@gmail.com</td>
      <td>4</td>
      <td>4</td>
      <td>4</td>
      <td>12</td>
    </tr>
    <tr>
      <td>3</td>
      <td>DEBBY</td>
      <td>1980-09-11</td>
      <td>L</td>
      <td>AB</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855555</td>
      <td>hihi@gmail.com</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>9</td>
    </tr>
    <tr>
      <td>4</td>
      <td>PATRI</td>
      <td>1977-08-01</td>
      <td>P</td>
      <td>A</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221827373</td>
      <td>hoho@gmail.com</td>
      <td>5</td>
      <td>4</td>
      <td>4</td>
      <td>13</td>
    </tr>
    <tr>
      <td>5</td>
      <td>ERNA</td>
      <td>1975-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221847373</td>
      <td>kkkk@gmail.com</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>9</td>
    </tr>
    <tr>
      <td>6</td>
      <td>AGUS</td>
      <td>1976-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221865555</td>
      <td>hahaha</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>7</td>
      <td>KIRA</td>
      <td>1975-10-11</td>
      <td>L</td>
      <td>AB</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855557</td>
      <td>hihi@gmail.com</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>8</td>
      <td>LANI</td>
      <td>1981-10-01</td>
      <td>P</td>
      <td>AB</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221821373</td>
      <td>hoho</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>9</td>
      <td>ORKA</td>
      <td>1976-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08121827373</td>
      <td>kkkk</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>10</td>
      <td>CAHYADI</td>
      <td>1976-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08121855555</td>
      <td>hahaha</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>11</td>
      <td>HUGO</td>
      <td>1976-11-24</td>
      <td>P</td>
      <td>A</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08220827373</td>
      <td>kkkk</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>12</td>
      <td>QURAIS</td>
      <td>1976-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>13</td>
      <td>VINA</td>
      <td>1980-10-11</td>
      <td>L</td>
      <td>A</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855555</td>
      <td>hihi@gmail.com</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <td>14</td>
      <td>SELENA</td>
      <td>1976-10-01</td>
      <td>P</td>
      <td>AB</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221827373</td>
      <td>hoho</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>15</td>
      <td>INTAN</td>
      <td>1976-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>16</td>
      <td>NATALIA</td>
      <td>1976-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>17</td>
      <td>YEREMIA</td>
      <td>1980-10-11</td>
      <td>L</td>
      <td>AB</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855555</td>
      <td>hihi@gmail.com</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <td>18</td>
      <td>TINA</td>
      <td>1980-10-01</td>
      <td>P</td>
      <td>AB</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221827373</td>
      <td>hoho</td>
      <td>1</td>
      <td>2</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <td>19</td>
      <td>XAXYONE</td>
      <td>1982-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk</td>
      <td>4</td>
      <td>1</td>
      <td>1</td>
      <td>6</td>
    </tr>
    <tr>
      <td>20</td>
      <td>FREDY</td>
      <td>1983-10-01</td>
      <td>L</td>
      <td>B</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>9</td>
    </tr>
    <tr>
      <td>21</td>
      <td>SATRIO</td>
      <td>1980-11-24</td>
      <td>P</td>
      <td>A</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk</td>
      <td>5</td>
      <td>4</td>
      <td>4</td>
      <td>13</td>
    </tr>
    <tr>
      <td>22</td>
      <td>GREGORI</td>
      <td>1980-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>23</td>
      <td>BUDI</td>
      <td>1980-10-11</td>
      <td>L</td>
      <td>AB</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855555</td>
      <td>hihi@gmail.com</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>24</td>
      <td>MESAKH</td>
      <td>1980-10-01</td>
      <td>P</td>
      <td>AB</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221827373</td>
      <td>hoho</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>7</td>
    </tr>
    <tr>
      <td>25</td>
      <td>NATAN</td>
      <td>1971-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk</td>
      <td>4</td>
      <td>3</td>
      <td>3</td>
      <td>10</td>
    </tr>
    <tr>
      <td>26</td>
      <td>PETER</td>
      <td>1972-10-01</td>
      <td>L</td>
      <td>O</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
    </tr>
    <tr>
      <td>27</td>
      <td>JEREMY</td>
      <td>1976-10-11</td>
      <td>L</td>
      <td>AB</td>
      <td>-</td>
      <td>hihi</td>
      <td>hihi</td>
      <td>08221855555</td>
      <td>hihi@gmail.com</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>9</td>
    </tr>
    <tr>
      <td>28</td>
      <td>URO</td>
      <td>1978-10-01</td>
      <td>P</td>
      <td>B</td>
      <td>+</td>
      <td>hoho</td>
      <td>hoho</td>
      <td>08221827373</td>
      <td>hoho</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <td>29</td>
      <td>RODAN</td>
      <td>1972-11-24</td>
      <td>P</td>
      <td>O</td>
      <td>+</td>
      <td>pakuwon city</td>
      <td>--</td>
      <td>08221827373</td>
      <td>kkkk</td>
      <td>2</td>
      <td>1</td>
      <td>1</td>
      <td>4</td>
    </tr>
    <tr>
      <td>30</td>
      <td>KUNCORO</td>
      <td>1973-10-01</td>
      <td>L</td>
      <td>A</td>
      <td>-</td>
      <td>hahahahaahha</td>
      <td>haha</td>
      <td>08221855555</td>
      <td>hahaha</td>
      <td>4</td>
      <td>4</td>
      <td>4</td>
      <td>12</td>
    </tr>
  </tbody>
</table>